config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :tags
  resources :tasks
  resources :tag_associations
  devise_for :users
  root to: "tasks#index"
  
  # Was redirect('/tasks')

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/tag_association.rb
class TagAssociation < ApplicationRecord
  belongs_to :tag
  belongs_to :task
end

app/controllers/tag_associations_controller.rb
class TagAssociationsController < ApplicationController
  before_action :set_tag_association, only: [:show, :edit, :update, :destroy]

  # GET /tag_associations
  # GET /tag_associations.json
  def index
    @tag_associations = TagAssociation.all
  end

  # GET /tag_associations/1
  # GET /tag_associations/1.json
  def show
  end

  # GET /tag_associations/new
  def new
    @tag_association = TagAssociation.new
  end

  # GET /tag_associations/1/edit
  def edit
  end

  # POST /tag_associations
  # POST /tag_associations.json
  def create
    @tag_association = TagAssociation.new(tag_association_params)

    respond_to do |format|
      if @tag_association.save
        format.html { redirect_to @tag_association, notice: 'Tag association was successfully created.' }
        format.json { render :show, status: :created, location: @tag_association }
      else
        format.html { render :new }
        format.json { render json: @tag_association.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tag_associations/1
  # PATCH/PUT /tag_associations/1.json
  def update
    respond_to do |format|
      if @tag_association.update(tag_association_params)
        format.html { redirect_to @tag_association, notice: 'Tag association was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag_association }
      else
        format.html { render :edit }
        format.json { render json: @tag_association.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_associations/1
  # DELETE /tag_associations/1.json
  def destroy
    @tag_association.destroy
    respond_to do |format|
      format.html { redirect_to tag_associations_url, notice: 'Tag association was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_association
      @tag_association = TagAssociation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_association_params
      params.require(:tag_association).permit(:tag_id, :task_id)
    end
end

app/helpers/tag_associations_helper.rb
module TagAssociationsHelper
end

app/views/tag_associations/_form.html.erb
<%= form_with(model: tag_association, local: true) do |form| %>
  <% if tag_association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag_association.errors.count, "error") %> prohibited this tag_association from being saved:</h2>

      <ul>
        <% tag_association.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tag_associations/edit.html.erb
<h1>Editing Tag Association</h1>

<%= render 'form', tag_association: @tag_association %>

<%= link_to 'Show', @tag_association %> |
<%= link_to 'Back', tag_associations_path %>

app/views/tag_associations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag Associations</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_associations.each do |tag_association| %>
      <tr>
        <td><%= tag_association.tag_id %></td>
        <td><%= tag_association.task_id %></td>
        <td><%= link_to 'Show', tag_association %></td>
        <td><%= link_to 'Edit', edit_tag_association_path(tag_association) %></td>
        <td><%= link_to 'Destroy', tag_association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag Association', new_tag_association_path %>

app/views/tag_associations/new.html.erb
<h1>New Tag Association</h1>

<%= render 'form', tag_association: @tag_association %>

<%= link_to 'Back', tag_associations_path %>

app/views/tag_associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tag_association.tag_id %>
</p>

<p>
  <strong>Task:</strong>
  <%= @tag_association.task_id %>
</p>

<%= link_to 'Edit', edit_tag_association_path(@tag_association) %> |
<%= link_to 'Back', tag_associations_path %>